export const products = [
  {
    id: "babor",
    brand: "BABOR",
    title: "Рождественский адвент-календарь 2025/26",
    meta: "Набор · 24 дня ухода",
    price: 8483,
    old: 9980,
    category: "Наборы",
    badge: "-15%",
    rating: 4.9,
    reviews: 124,
    image: "img/placeholder-01.webp",
    stock: true,
  },
  {
    id: "allure",
    brand: "KAMALI",
    title: "Диффузор для дома ALLURE",
    meta: "Аромат для дома · 100 мл",
    price: 1490,
    old: 0,
    category: "Парфюм",
    badge: "ХИТ",
    rating: 4.8,
    reviews: 161,
    image: "img/placeholder-02.webp",
    stock: true,
  },
  {
    id: "amore",
    brand: "KAMALI",
    title: "Диффузор для дома AMORE 62",
    meta: "Аромат для дома · 100 мл",
    price: 1490,
    old: 0,
    category: "Парфюм",
    badge: "НОВИНКА",
    rating: 4.8,
    reviews: 198,
    image: "img/placeholder-03.webp",
    stock: true,
  },
  {
    id: "crystal",
    brand: "KAMALI",
    title: "Диффузор для дома CRYSTAL",
    meta: "Аромат для дома · 100 мл",
    price: 1490,
    old: 0,
    category: "Парфюм",
    badge: "",
    rating: 4.9,
    reviews: 235,
    image: "img/placeholder-04.webp",
    stock: true,
  },
  {
    id: "intrigue",
    brand: "KAMALI",
    title: "Крем для волос INTRIGUE",
    meta: "Несмываемый уход · 250 мл",
    price: 690,
    old: 0,
    category: "Волосы",
    badge: "НОВИНКА",
    rating: 4.8,
    reviews: 272,
    image: "img/placeholder-05.webp",
    stock: true,
  },
  {
    id: "legend",
    brand: "KAMALI",
    title: "Мист для тела и волос LEGEND",
    meta: "Мист · 250 мл",
    price: 690,
    old: 0,
    category: "Тело",
    badge: "",
    rating: 4.8,
    reviews: 309,
    image: "img/placeholder-06.webp",
    stock: true,
  },
  {
    id: "laneige",
    brand: "LANEIGE",
    title: "Восстанавливающая и увлажняющая маска",
    meta: "Маска · 15 мл",
    price: 590,
    old: 0,
    category: "Лицо",
    badge: "ХИТ",
    rating: 4.9,
    reviews: 346,
    image: "img/placeholder-07.webp",
    stock: true,
  },
  {
    id: "marvis",
    brand: "MARVIS",
    title: "Зубная паста «Мята и имбирь»",
    meta: "Уход за полостью рта · 25 мл",
    price: 490,
    old: 0,
    category: "Аксессуары",
    badge: "",
    rating: 4.8,
    reviews: 383,
    image: "img/placeholder-08.webp",
    stock: true,
  },
  {
    id: "pusy",
    brand: "PUSY",
    title: "Автозагар для лица",
    meta: "Автозагар · 100 мл",
    price: 990,
    old: 0,
    category: "Лицо",
    badge: "НОВИНКА",
    rating: 4.8,
    reviews: 420,
    image: "img/placeholder-09.webp",
    stock: true,
  },
  {
    id: "minu",
    brand: "DAVINES",
    title: "MINU Маска для волос",
    meta: "Маска · 250 мл",
    price: 5100,
    old: 0,
    category: "Волосы",
    badge: "ХИТ",
    rating: 4.9,
    reviews: 457,
    image: "img/placeholder-10.webp",
    stock: true,
  },
  {
    id: "love",
    brand: "DAVINES",
    title: "LOVE smoothing Шампунь",
    meta: "Шампунь · 250 мл",
    price: 3560,
    old: 0,
    category: "Волосы",
    badge: "",
    rating: 4.8,
    reviews: 494,
    image: "img/placeholder-11.webp",
    stock: true,
  },
  {
    id: "shik",
    brand: "SHIK",
    title: "Бальзам-стик для губ 02 BLOSSOM",
    meta: "Уход за губами",
    price: 840,
    old: 0,
    category: "Макияж",
    badge: "НОВИНКА",
    rating: 4.8,
    reviews: 531,
    image: "img/placeholder-12.webp",
    stock: true,
  },
  {
    id: "axis",
    brand: "AXIS-Y",
    title: "Quinoa One Step Balanced Gel Cleanser",
    meta: "Очищающий гель · 180 мл",
    price: 1478,
    old: 2090,
    category: "Лицо",
    badge: "-29%",
    rating: 4.9,
    reviews: 568,
    image: "img/placeholder-13.webp",
    stock: true,
  },
  {
    id: "rare",
    brand: "RARE BEAUTY",
    title: "Positive Light Tinted Moisturizer",
    meta: "Тональное средство · 30 мл",
    price: 3520,
    old: 4690,
    category: "Макияж",
    badge: "ХИТ",
    rating: 4.8,
    reviews: 605,
    image: "img/placeholder-14.webp",
    stock: true,
  },
  {
    id: "oi",
    brand: "DAVINES",
    title: "OI All in One Milk",
    meta: "Несмываемое молочко · 135 мл",
    price: 7240,
    old: 0,
    category: "Волосы",
    badge: "ХИТ",
    rating: 4.8,
    reviews: 642,
    image: "img/placeholder-15.webp",
    stock: true,
  },
  {
    id: "dalba",
    brand: "D’ALBA",
    title: "White Truffle First Spray Serum",
    meta: "Спрей-сыворотка · 100 мл",
    price: 2755,
    old: 0,
    category: "Лицо",
    badge: "НОВИНКА",
    rating: 4.9,
    reviews: 679,
    image: "img/placeholder-16.webp",
    stock: true,
  },
  {
    id: "celimax",
    brand: "CELIMAX",
    title: "Dual Barrier Boosting Serum",
    meta: "Сыворотка для барьера · 30 мл",
    price: 1138,
    old: 0,
    category: "Лицо",
    badge: "",
    rating: 4.8,
    reviews: 716,
    image: "img/placeholder-17.webp",
    stock: true,
  },
  {
    id: "retinol",
    brand: "CELIMAX",
    title: "Retinol Shot Tightening Serum",
    meta: "Сыворотка с ретинолом · 30 мл",
    price: 1116,
    old: 0,
    category: "Лицо",
    badge: "НОВИНКА",
    rating: 4.8,
    reviews: 753,
    image: "img/placeholder-18.webp",
    stock: true,
  },
];
